name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=HellMan1721_python-project-52
            -Dsonar.organization=hellman1721
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/migrations/**,**/tests/**,**/__init__.py,manage.py,**/admin.py,**/wsgi.py,**/asgi.py,**/settings.py
            -Dsonar.coverage.exclusions=**/migrations/**,**/tests/**,**/__init__.py,manage.py,**/admin.py,**/wsgi.py,**/asgi.py,**/settings.py,**/urls.py